// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const ensureStatements = `-- name: EnsureStatements :batchone
INSERT INTO statements (server_name, database_name, user_name, query_id, query_text)
VALUES ($1, $2, $3, $4, '')
ON CONFLICT (server_name, database_name, user_name, query_id)
DO UPDATE SET query_text = EXCLUDED.query_text
RETURNING id
`

type EnsureStatementsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type EnsureStatementsParams struct {
	ServerName   string
	DatabaseName string
	UserName     string
	QueryID      int64
}

func (q *Queries) EnsureStatements(ctx context.Context, arg []EnsureStatementsParams) *EnsureStatementsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ServerName,
			a.DatabaseName,
			a.UserName,
			a.QueryID,
		}
		batch.Queue(ensureStatements, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &EnsureStatementsBatchResults{br, len(arg), false}
}

func (b *EnsureStatementsBatchResults) QueryRow(f func(int, int64, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var id int64
		if b.closed {
			if f != nil {
				f(t, id, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(&id)
		if f != nil {
			f(t, id, err)
		}
	}
}

func (b *EnsureStatementsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertLogEvents = `-- name: InsertLogEvents :batchone
INSERT INTO log_events (
    server_name, collected_at, occurred_at, log_level, classification, message,
    pid, username, database_name, application_name, detail, hint, context,
    statement, backend_type, state_code
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
RETURNING id
`

type InsertLogEventsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertLogEventsParams struct {
	ServerName      string
	CollectedAt     pgtype.Timestamptz
	OccurredAt      pgtype.Timestamptz
	LogLevel        int32
	Classification  int32
	Message         string
	Pid             pgtype.Int4
	Username        pgtype.Text
	DatabaseName    pgtype.Text
	ApplicationName pgtype.Text
	Detail          pgtype.Text
	Hint            pgtype.Text
	Context         pgtype.Text
	Statement       pgtype.Text
	BackendType     pgtype.Text
	StateCode       pgtype.Text
}

func (q *Queries) InsertLogEvents(ctx context.Context, arg []InsertLogEventsParams) *InsertLogEventsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ServerName,
			a.CollectedAt,
			a.OccurredAt,
			a.LogLevel,
			a.Classification,
			a.Message,
			a.Pid,
			a.Username,
			a.DatabaseName,
			a.ApplicationName,
			a.Detail,
			a.Hint,
			a.Context,
			a.Statement,
			a.BackendType,
			a.StateCode,
		}
		batch.Queue(insertLogEvents, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertLogEventsBatchResults{br, len(arg), false}
}

func (b *InsertLogEventsBatchResults) QueryRow(f func(int, int64, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var id int64
		if b.closed {
			if f != nil {
				f(t, id, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(&id)
		if f != nil {
			f(t, id, err)
		}
	}
}

func (b *InsertLogEventsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const recordTransactionEvent = `-- name: RecordTransactionEvent :batchexec
WITH params AS (
    SELECT
        $1::text            AS server_name,
        $2::int                     AS pid,
        $3::timestamptz   AS backend_start,
        $4::timestamptz      AS xact_start,
        $5::text          AS database_name,
        $6::text              AS user_name,
        $7::text       AS application_name,
        $8::timestamptz    AS collected_at,
        $9::text                  AS state,
        $10::text        AS wait_event_type,
        $11::text             AS wait_event,
        $12::timestamptz     AS query_start,
        $13::bigint         AS statement_id,
        $14::text                  AS query,
        $15::jsonb            AS query_tags,
        $16::int          AS blocked_by_pid,
        $17::timestamptz AS lock_wait_start,
        $18::text              AS lock_mode
),
norm AS (
    SELECT
        NULLIF(wait_event_type, '') AS wait_event_type,
        NULLIF(wait_event, '')      AS wait_event,
        NULLIF(query, '')           AS query,
        NULLIF(lock_mode, '')       AS lock_mode,
        NULLIF(blocked_by_pid, 0)   AS blocked_by_pid,
        NULLIF(statement_id, 0)     AS statement_id
    FROM params
),
tx AS (
    INSERT INTO transactions (
        server_name, pid, backend_start, xact_start,
        database_name, user_name, application_name, last_seen_at
    )
    SELECT
        server_name, pid, backend_start, xact_start,
        database_name, user_name, application_name, collected_at
    FROM params
    ON CONFLICT (server_name, pid, backend_start, xact_start)
    DO UPDATE SET last_seen_at = GREATEST(transactions.last_seen_at, EXCLUDED.last_seen_at)
    RETURNING id
),
latest AS (
    SELECT e.id, e.state, e.wait_event_type, e.wait_event, e.transaction_query_id, q.query_start,
           e.blocked_by_pid, e.lock_wait_start, e.lock_mode
    FROM transaction_events e
    JOIN transaction_queries q ON q.id = e.transaction_query_id
    JOIN tx ON q.transaction_id = tx.id
    ORDER BY e.first_seen_at DESC, e.id DESC
    LIMIT 1
),
tq_ins AS (
    INSERT INTO transaction_queries (transaction_id, xact_start, query_start, statement_id, query, query_tags)
    SELECT tx.id, params.xact_start, params.query_start, norm.statement_id, norm.query, params.query_tags
    FROM tx, norm, params
    WHERE params.query_start IS DISTINCT FROM (SELECT query_start FROM latest)
    ON CONFLICT (transaction_id, query_start, xact_start) DO NOTHING
    RETURNING id
),
tq AS (
    SELECT coalesce(
        (SELECT id FROM tq_ins),
        (SELECT q.id FROM transaction_queries q JOIN tx ON q.transaction_id = tx.id
         WHERE q.query_start IS NOT DISTINCT FROM params.query_start)
    ) AS id
    FROM params
),
extended AS (
    UPDATE transaction_events e
    SET last_seen_at = GREATEST(e.last_seen_at, params.collected_at)
    FROM latest, norm, tq, params
    WHERE e.id = latest.id
      AND latest.transaction_query_id IS NOT DISTINCT FROM tq.id
      AND latest.state           IS NOT DISTINCT FROM params.state
      AND latest.wait_event_type IS NOT DISTINCT FROM norm.wait_event_type
      AND latest.wait_event      IS NOT DISTINCT FROM norm.wait_event
      AND latest.blocked_by_pid  IS NOT DISTINCT FROM norm.blocked_by_pid
      AND latest.lock_wait_start IS NOT DISTINCT FROM params.lock_wait_start
      AND latest.lock_mode       IS NOT DISTINCT FROM norm.lock_mode
    RETURNING e.id
)
INSERT INTO transaction_events (
    transaction_query_id, xact_start, state, wait_event_type, wait_event,
    blocked_by_pid, lock_wait_start, lock_mode, first_seen_at, last_seen_at
)
SELECT tq.id, params.xact_start, params.state, norm.wait_event_type, norm.wait_event,
       norm.blocked_by_pid, params.lock_wait_start, norm.lock_mode, params.collected_at, params.collected_at
FROM tq, norm, params
WHERE NOT EXISTS (SELECT 1 FROM extended)
`

type RecordTransactionEventBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type RecordTransactionEventParams struct {
	ServerName      string
	Pid             int32
	BackendStart    pgtype.Timestamptz
	XactStart       pgtype.Timestamptz
	DatabaseName    string
	UserName        string
	ApplicationName string
	CollectedAt     pgtype.Timestamptz
	State           string
	WaitEventType   string
	WaitEvent       string
	QueryStart      pgtype.Timestamptz
	StatementID     int64
	Query           string
	QueryTags       []byte
	BlockedByPid    int32
	LockWaitStart   pgtype.Timestamptz
	LockMode        string
}

func (q *Queries) RecordTransactionEvent(ctx context.Context, arg []RecordTransactionEventParams) *RecordTransactionEventBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ServerName,
			a.Pid,
			a.BackendStart,
			a.XactStart,
			a.DatabaseName,
			a.UserName,
			a.ApplicationName,
			a.CollectedAt,
			a.State,
			a.WaitEventType,
			a.WaitEvent,
			a.QueryStart,
			a.StatementID,
			a.Query,
			a.QueryTags,
			a.BlockedByPid,
			a.LockWaitStart,
			a.LockMode,
		}
		batch.Queue(recordTransactionEvent, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &RecordTransactionEventBatchResults{br, len(arg), false}
}

func (b *RecordTransactionEventBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *RecordTransactionEventBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertAlertToggle = `-- name: UpsertAlertToggle :batchexec
INSERT INTO alert_toggles (server_name, alert_key, enabled)
VALUES ($1, $2, $3)
ON CONFLICT (server_name, alert_key) DO UPDATE SET enabled = EXCLUDED.enabled
`

type UpsertAlertToggleBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertAlertToggleParams struct {
	ServerName string
	AlertKey   string
	Enabled    bool
}

func (q *Queries) UpsertAlertToggle(ctx context.Context, arg []UpsertAlertToggleParams) *UpsertAlertToggleBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ServerName,
			a.AlertKey,
			a.Enabled,
		}
		batch.Queue(upsertAlertToggle, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertAlertToggleBatchResults{br, len(arg), false}
}

func (b *UpsertAlertToggleBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertAlertToggleBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertStatements = `-- name: UpsertStatements :batchone
INSERT INTO statements (server_name, database_name, user_name, query_id, query_text)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (server_name, database_name, user_name, query_id)
DO UPDATE SET query_text = EXCLUDED.query_text
RETURNING id
`

type UpsertStatementsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertStatementsParams struct {
	ServerName   string
	DatabaseName string
	UserName     string
	QueryID      int64
	QueryText    string
}

func (q *Queries) UpsertStatements(ctx context.Context, arg []UpsertStatementsParams) *UpsertStatementsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ServerName,
			a.DatabaseName,
			a.UserName,
			a.QueryID,
			a.QueryText,
		}
		batch.Queue(upsertStatements, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertStatementsBatchResults{br, len(arg), false}
}

func (b *UpsertStatementsBatchResults) QueryRow(f func(int, int64, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var id int64
		if b.closed {
			if f != nil {
				f(t, id, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(&id)
		if f != nil {
			f(t, id, err)
		}
	}
}

func (b *UpsertStatementsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
