// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertStatementDeltas implements pgx.CopyFromSource.
type iteratorForInsertStatementDeltas struct {
	rows                 []InsertStatementDeltasParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertStatementDeltas) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertStatementDeltas) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].StatementID,
		r.rows[0].CollectedAt,
		r.rows[0].Calls,
		r.rows[0].Rows,
		r.rows[0].TotalExecTime,
		r.rows[0].SharedBlksRead,
		r.rows[0].TempBlksWritten,
	}, nil
}

func (r iteratorForInsertStatementDeltas) Err() error {
	return nil
}

func (q *Queries) InsertStatementDeltas(ctx context.Context, arg []InsertStatementDeltasParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"statement_deltas"}, []string{"statement_id", "collected_at", "calls", "rows", "total_exec_time", "shared_blks_read", "temp_blks_written"}, &iteratorForInsertStatementDeltas{rows: arg})
}

// iteratorForInsertStatementSamples implements pgx.CopyFromSource.
type iteratorForInsertStatementSamples struct {
	rows                 []InsertStatementSamplesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertStatementSamples) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertStatementSamples) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ServerName,
		r.rows[0].CollectedAt,
		r.rows[0].OccurredAt,
		r.rows[0].LogEventID,
		r.rows[0].StatementID,
		r.rows[0].Query,
		r.rows[0].DurationMs,
		r.rows[0].Parameters,
		r.rows[0].ExplainPlanJson,
		r.rows[0].Tags,
	}, nil
}

func (r iteratorForInsertStatementSamples) Err() error {
	return nil
}

func (q *Queries) InsertStatementSamples(ctx context.Context, arg []InsertStatementSamplesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"statement_samples"}, []string{"server_name", "collected_at", "occurred_at", "log_event_id", "statement_id", "query", "duration_ms", "parameters", "explain_plan_json", "tags"}, &iteratorForInsertStatementSamples{rows: arg})
}
